version: "3"
services:
  postgres:
    image: postgres:14
    container_name: postgresql
    networks:
      - db-net
    env_file: ./postgres_env
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"
  pgadmin:
    image: dpage/pgadmin4:6.8
    container_name: pg-admin
    networks:
      - db-net
    env_file: ./pgadmin_env
    ports:
      - "80:80"
    volumes:
      - "./pgadmin-data:/var/lib/pgadmin"

networks:
  db-net:
  	driver: bridge
